### PR TITLE
Bunch of fixes to provide smooth build experience

### PR DESCRIPTION
**Pull request by orsonmmz**
The proposed changes have been tested on macOS 10.13.4.

### CODE REVIEW

**Comment by adamwolf** [comment]
Thanks!  This'll help fix the nightlies!  

I'll port these changes to https://github.com/wayneandlayne/kicad-mac-builder, the "next generation" packaging stuff, unless you want to.

**Comment by orsonmmz** [comment]
Great, thanks for quick reaction! I would be grateful if you could port the changes, I am having a hard time using a Mac. I suppose it is just a matter of habits.

**Comment by orsonmmz** [comment]
I think the nightlies are fine, as there is an up-to-date .dmg package available. I aimed at improving the new user build experience.

**Comment by adamwolf** [comment]
No problem, already started over at https://github.com/wayneandlayne/kicad-mac-builder/pull/70.

**Comment by orsonmmz** [comment]
Not sure, if it is still relevant, but I got a question regarding Resources directory in oce package. I also have oce 0.18.2 installed and Resources directory contains just a bunch of cmake scripts:
```
orson@twl-mac ~ $ brew list --verbose oce | grep Resources
/usr/local/Cellar/oce/0.18.2/OCE.framework/Versions/0.18/Resources/OCEConfig.cmake
/usr/local/Cellar/oce/0.18.2/OCE.framework/Versions/0.18/Resources/OCE-libraries.cmake
/usr/local/Cellar/oce/0.18.2/OCE.framework/Versions/0.18/Resources/OCEConfigVersion.cmake
/usr/local/Cellar/oce/0.18.2/OCE.framework/Versions/0.18/Resources/OCE-libraries-release.cmake
```

**Pull request merged**
